#pragma once
#include <cstddef>

/* The built web bundle, compiled into the binary.
*
* Generated by cmake/EmbedWebAssets.cmake from Web/dist at build time. `path` is relative
* and uses forward slashes, so it matches what a browser asks for: "index.html",
* "assets/index-abc123.js".
*
* An empty table is a supported state, not a failure -- a machine without npm still builds
* everything else, and the app says the UI was not built in rather than refusing to start.
*/
struct EmbeddedAsset {
	const char* path;
	const unsigned char* data;
	size_t size;
};

/* The asset table. `count` is set to its length, which may be 0. */
const EmbeddedAsset* embeddedWebAssets(size_t& count);
