# Turn a built web bundle into a C++ translation unit.
#
# Run in script mode:
#   cmake -DASSET_DIR=<dist> -DOUTPUT=<generated.cpp> -P EmbedWebAssets.cmake
#
# Emits one byte array per file plus a table of {path, data, size}. Paths are stored with
# forward slashes and relative to ASSET_DIR, so they match what a browser asks for.
#
# Byte arrays rather than string literals on purpose: MSVC caps a string literal at 65,535
# bytes and the JS bundle is comfortably past that, so literals would compile on a small
# build and then fail on a real one.
#
# An absent or empty ASSET_DIR is not an error. It produces an empty table, the app reports
# that no UI was built in, and the engine still runs -- a machine without npm can still
# build everything else.

if(NOT DEFINED OUTPUT)
	message(FATAL_ERROR "EmbedWebAssets: OUTPUT not set")
endif()

set(files "")
if(DEFINED ASSET_DIR AND EXISTS "${ASSET_DIR}")
	file(GLOB_RECURSE files RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*")
endif()

set(arrays "")
set(entries "")
set(index 0)
set(totalBytes 0)

foreach(file IN LISTS files)
	if(IS_DIRECTORY "${ASSET_DIR}/${file}")
		continue()
	endif()

	file(READ "${ASSET_DIR}/${file}" hex HEX)
	string(LENGTH "${hex}" hexLength)
	math(EXPR byteCount "${hexLength} / 2")
	math(EXPR totalBytes "${totalBytes} + ${byteCount}")

	# Split into 0x.. literals, wrapping so the generated file is not one enormous line.
	# MSVC copes with long lines but debuggers and diffs do not.
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
	string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n\t" bytes "${bytes}")

	string(APPEND arrays
		"const unsigned char asset_${index}[] = {\n\t${bytes}\n};\n\n")
	string(APPEND entries
		"\t{ \"${file}\", asset_${index}, ${byteCount}u },\n")

	math(EXPR index "${index} + 1")
endforeach()

if(index EQUAL 0)
	set(arrays "")
	set(entries "")
	set(tableBody "\tstatic const EmbeddedAsset empty[1] = { { nullptr, nullptr, 0u } };\n\tcount = 0;\n\treturn empty;")
else()
	set(tableBody "\tcount = sizeof(kAssets) / sizeof(kAssets[0]);\n\treturn kAssets;")
endif()

if(index EQUAL 0)
	set(table "")
else()
	set(table "const EmbeddedAsset kAssets[] = {\n${entries}};\n\n")
endif()

file(WRITE "${OUTPUT}"
"// GENERATED by cmake/EmbedWebAssets.cmake -- do not edit.
// Source: ${ASSET_DIR}
// ${index} file(s), ${totalBytes} bytes.

#include \"EmbeddedWeb.h\"

namespace {

${arrays}${table}} // namespace

const EmbeddedAsset* embeddedWebAssets(size_t& count) {
${tableBody}
}
")

message(STATUS "EmbedWebAssets: ${index} file(s), ${totalBytes} bytes -> ${OUTPUT}")
